USE [master]
GO

/****** Object:  Database [sipbb]    Script Date: 12-Aug-18 1:20:47 PM ******/
CREATE DATABASE [sipbb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'sipbb', FILENAME = N'C:\ProgramData\SOLIDWORKS Electrical\MSSQL12.TEW_SQLEXPRESS\MSSQL\DATA\sipbb.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'sipbb_log', FILENAME = N'C:\ProgramData\SOLIDWORKS Electrical\MSSQL12.TEW_SQLEXPRESS\MSSQL\DATA\sipbb_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [sipbb] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [sipbb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [sipbb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [sipbb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [sipbb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [sipbb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [sipbb] SET ARITHABORT OFF 
GO

ALTER DATABASE [sipbb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [sipbb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [sipbb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [sipbb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [sipbb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [sipbb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [sipbb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [sipbb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [sipbb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [sipbb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [sipbb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [sipbb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [sipbb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [sipbb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [sipbb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [sipbb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [sipbb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [sipbb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [sipbb] SET  MULTI_USER 
GO

ALTER DATABASE [sipbb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [sipbb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [sipbb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [sipbb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [sipbb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [sipbb] SET  READ_WRITE 
GO

